CREATE TABLE inc.errores  ( Id_Error INT NOT NULL,  
Id_Pantalla INT NOT NULL,  
Codigo VARCHAR(10) NOT NULL,  
Descripcion VARCHAR(250) NOT NULL,  
Pasos_Reprod VARCHAR(250) NOT NULL,  
Id_Tipo_Prob INT NOT NULL,  
PRIMARY KEY (Id_Error),  
INDEX Id_Pantalla_FK_idx (Id_Pantalla ASC),
INDEX Id_TipoProb_idx (Id_Tipo_Prob ASC), 
CONSTRAINT Id_Pantalla_FK    FOREIGN KEY (Id_Pantalla)    REFERENCES inc.pantallas (Id_Pantalla), 
CONSTRAINT Id_Tipo_Prob_FK    FOREIGN KEY (Id_Tipo_Prob)    REFERENCES inc.tipo_problema (Id_Tipo_Prob));

  
CREATE TABLE inc.soluciones ( Id_Solucion INT NOT NULL,  
Desc_Corta  VARCHAR(30) NOT NULL,  
Desc_Larga VARCHAR(250) NOT NULL, 
Id_Resolutor INT NOT NULL,  
Fecha Date NOT NULL,  
Anexo  LONGBLOB,
Id_Error INT NOT NULL,  
Tipo_Usuario boolean NOT NULL, 
Desc_Path varchar(100), 
Permisos varchar(250), 
Prerequisitos varchar(250), 
Script varchar(250), 
Herramienta varchar(100),
PRIMARY KEY (Id_Solucion),  
INDEX Id_Resolutor_FK_idx (Id_Resolutor ASC), INDEX Id_Error_FK_idx (Id_Error ASC), 
CONSTRAINT Id_Resolutor_FK    FOREIGN KEY (Id_Resolutor)    REFERENCES inc.resolutores (Id_Resolutor),
CONSTRAINT Id_Error_FK    FOREIGN KEY (Id_Error)    REFERENCES inc.errores (Id_Error));



CREATE TABLE inc.incidentes ( Id_Incidente INT NOT NULL,  
Id_Usuario INT NOT NULL,  
Id_Resolutor INT,  
Fecha Date NOT NULL,  
Anexo  LONGBLOB,
Id_Error INT NOT NULL,  
Prioridad INT NOT NULL,
Id_Estado INT NOT NULL, 
Id_Solucion INT, 
PRIMARY KEY (Id_Incidente),  
INDEX Id_Res_FK (Id_Resolutor ASC),
INDEX Id_Err_FK_idx (Id_Error ASC), 
INDEX Id_Sol_FK_idx (Id_Solucion ASC), 
INDEX Id_Est_FK_idx (Id_Estado ASC), 
INDEX Id_Usu_FK_idx (Id_Usuario ASC), 
CONSTRAINT Id_Res_FK    FOREIGN KEY (Id_Resolutor)    REFERENCES inc.resolutores (Id_Resolutor)   ,  
CONSTRAINT Id_Err_FK    FOREIGN KEY (Id_Error)    REFERENCES inc.errores (Id_Error)  ,
CONSTRAINT Id_Sol_FK    FOREIGN KEY (Id_Solucion)    REFERENCES inc.soluciones (Id_Solucion) , 
CONSTRAINT Id_Est_FK    FOREIGN KEY (Id_Estado)    REFERENCES inc.estados (Id_Estado)    , 
CONSTRAINT Id_Usu_FK    FOREIGN KEY (Id_Usuario)    REFERENCES inc.usuarios (Id_Usuario));
